name: Deploy React App
on: ["push","workflow_dispatch"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: Set up NodeJS
              uses: actions/setup-node@v6
              with:
                node-version: 16
            - name: Install npm libraries
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Test
              run: npm run test
            - name: Deploy
              run: echo "Deployed successfully"